Text_SwordsDanceTeach::
    .string "Not many people come out here.\p"
    .string "If I train here, I'm convinced that\n"
    .string "I'll get stronger and stronger.\p"
    .string "Yep, stronger and stronger…\p"
    .string "How would you like to learn a move\n"
    .string "like that? It's {STR_VAR_1}.$"

Text_SwordsDanceDeclined::
    .string "Well, that's fine, too.$"

Text_SwordsDanceWhichMon::
    .string "All right, pick which POKéMON\n"
    .string "I should teach it to.$"

Text_SwordsDanceTaught::
    .string "If only we could keep getting\n"
    .string "stronger and stronger, eh?$"

SevenIsland_Text_IslandSign::
    .string "SEVEN ISLAND\n"
    .string "Quest Island of Infinity$"

SevenIsland_Text_IslandsMadeInSevenDays::
    .string "These islands are called the SEVII\n"
    .string "ISLANDS because there are seven.\p"
    .string "…Or at least that's what the young\n"
    .string "people believe.\p"
    .string "The truth is, these islands are so\n"
    .string "named because they are said to\l"
    .string "have been made in seven days.$"

SevenIsland_Text_ColleagueLostScanner::
    .string "A colleague of mine visited this\n"
    .string "island many years ago.\p"
    .string "He lost our SCANNER that we used\n"
    .string "for researching WATER-type POKéMON.$"

SevenIsland_Text_CanIHaveIt::
    .string "Oh?\n"
    .string "That item you have there.\p"
    .string "It's the SCANNER my colleague lost\n"
    .string "all those years ago.\p"
    .string "Would you mind giving it to me?\n"
    .string "I'll give you this DEEPSEA SCALE\l"
    .string "and DEEPSEA TOOTH that I have.$"

SevenIsland_Text_HandedScanner::
    .string "{PLAYER} handed the SCANNER\n"
    .string "to the SCIENTIST.$"

SevenIsland_Text_AreYouSure::
    .string "Are you sure? I doubt it will be\n"
    .string "of much use to you.\p"
    .string "Well, if you change your mind just\n"
    .string "let me know.$"

SevenIsland_Text_GetBackToResearch::
    .string "Thank you! Now we can get back to\n"
    .string "our research.$"

