CeladonCity_Condominiums_1F_Text_Meowth::
    .string "MEOWTH: Meow!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "You shouldn't spend all your money\n"
    .string "on drinks.\p"
    .string "Try this instead.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Nothing beats thirst like some hot\n"
    .string "TEA.\p"
    .string "It really is the best.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "My dear POKéMON keep me company.\n"
    .string "MEOWTH even brings money home!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Oh, hello, dearie.\n"
    .string "Did you enjoy my TEA?\p"
    .string "By the way, dear. Are you, by any\n"
    .string "chance, from PALLET TOWN?\p"
    .string "A girl from PALLET TOWN, DAISY,\n"
    .string "she enjoys TEA every day.\p"
    .string "She visits the CELADON DEPT. STORE\n"
    .string "to buy some TEA.$"

CeladonCity_Condominiums_1F_Text_TravelingAroundKanto::
	.string "I've been traveling around KANTO\n"
	.string "in search of more fossils.\p"
	.string "Although, I've currently decided\n"
	.string "to stop and have some TEA.\p"
	.string "I'll let you have some.$"

CeladonCity_Condominiums_1F_Text_NiceAndRelaxing::
	.string "Sitting down and drinking a cup of\n"
	.string "TEA is nice and relaxing.$"

CeladonCity_Condominiums_1F_Text_JourneyGoingWell::
	.string "Has your journey to collect BADGES\n"
	.string "been going well?\p"
	.string "Make sure you raise all your\n"
	.string "POKéMON well.$"

CeladonCity_Condominiums_1F_Text_TrySomeTea::
	.string "I heard that CELADON CITY is known\n"
	.string "for its large variety of drinks.\p"
	.string "I'm currently trying some TEA that\n"
	.string "I heard was very popular.\p"
	.string "You should try it too.$"

CeladonCity_Condominiums_1F_Text_HelpWithSwimming::
	.string "I wonder if this TEA will help me\n"
	.string "with my swimming.$"

CeladonCity_Condominiums_1F_Text_ShouldBeHeadingBack::
	.string "I really should start heading back to\n"
	.string "CERULEAN CITY soon.$"

CeladonCity_Condominiums_1F_Text_TakingABreak::
	.string "Still cataloging POKéMON?\n"
	.string "I hope it isn't too exhausting.\p"
	.string "I often come here to try out new\n"
	.string "flavors of TEA.\p"
	.string "Here, you should try this one.$"

CeladonCity_Condominiums_1F_Text_SupposedlyGoodForYou::
	.string "Supposedly that TEA is very good\n"
	.string "for you. I hope you enjoy it.$"

CeladonCity_Condominiums_1F_Text_HowIsYourJourney::
	.string "How is your journey to catalog\n"
	.string "POKéMON going?\p"
	.string "Don't forget that you should take\n"
	.string "a break every once in a while.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "CLEFAIRY: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "NIDORAN♀: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "CELADON MANSION\n"
    .string "Manager's Suite$"

