#ifndef GUARD_CONSTANTS_SHOPS_H
#define GUARD_CONSTANTS_SHOPS_H

#define SHOP_BETTER 0
#define SHOP_VIRIDIAN_CITY 1
#define SHOP_PEWTER_CITY 2
#define SHOP_CERULEAN_CITY 3
#define SHOP_VERMILION_CITY 4
#define SHOP_LAVENDER_TOWN 5
#define SHOP_CELADON_DEPT_ITEM_SHOP 6
#define SHOP_CELADON_DEPT_TM_SHOP 7
#define SHOP_CELADON_DEPT_EVO_SHOP 8
#define SHOP_CELADON_DEPT_HELD_SHOP 9
#define SHOP_CELADON_DEPT_BATTLE_SHOP 10
#define SHOP_CELADON_DEPT_VITAMIN_SHOP 11
#define SHOP_FUCHSIA_CITY 12
#define SHOP_SAFFRON_CITY 13
#define SHOP_CINNABAR_ISLAND 14
#define SHOP_INDIGO_PLATEAU 15
#define SHOP_TWO_ISLAND_INITIAL 16
#define SHOP_TWO_ISLAND_EXPANDED_1 17
#define SHOP_TWO_ISLAND_EXPANDED_2 18
#define SHOP_TWO_ISLAND_EXPANDED_3 19
#define SHOP_THREE_ISLAND 20
#define SHOP_FOUR_ISLAND 21
#define SHOP_SIX_ISLAND 22
#define SHOP_SEVEN_ISLAND 23
#define SHOP_TRAINER_TOWER 24
#define SHOP_POKEMON_CENTER 25

#define SHOPSANITY_FIRST_INDEX SHOP_VIRIDIAN_CITY
#define SHOPSANITY_LAST_INDEX SHOP_TRAINER_TOWER

#define TWO_ISLAND_SHOP_ITEM_COUNT 9

#endif  // GUARD_CONSTANTS_SHOPS_H
