CinnabarIsland_PokemonLab_ResearchRoom_Text_TakeThisLetter::
    .string "Would you be willing to help me\n"
    .string "with my research?\p"
    .string "I would like you to head to the\n"
    .string "POKéMON MANSION north of here and\l"
    .string "bring back any documents you find.\p"
    .string "Show this to the POLICEMAN\n"
    .string "guarding the entrance and he\l"
    .string "will let you in.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "EEVEE can evolve into one of three\n"
    .string "kinds of POKéMON.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "There's an e-mail message.\p"
    .string "… … …\p"
    .string "There are three legendary bird\n"
    .string "POKéMON.\p"
    .string "They are ARTICUNO, ZAPDOS, and\n"
    .string "MOLTRES.\p"
    .string "Their whereabouts are unknown.\p"
    .string "We plan to explore the cavern\n"
    .string "close to CERULEAN.\p"
    .string "From: POKéMON RESEARCH TEAM…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "An amber pipe!$"

