Aide_Text_HaventCaughtEnoughMonsForItem::
  .string "Let's see…\n"
  .string "Uh-oh! You have caught only\l"
  .string "{STR_VAR_4} kinds of POKéMON!\p"
  .string "You need {STR_VAR_1} kinds\n"
  .string "if you want the {STR_VAR_3}.$"

Aide_Text_HaventCaughtEnoughMonsForPlayerItem::
  .string "Let's see…\n"
  .string "Uh-oh! You have caught only\l"
  .string "{STR_VAR_4} kinds of POKéMON!\p"
  .string "You need {STR_VAR_1} kinds\n"
  .string "if you want {STR_VAR_2}'s\l"
  .string "{STR_VAR_3}.$"

Aide_Text_NoPokedexComeBackForItem::
  .string "…Oh. You don't have a POKéDEX.\p"
  .string "When you get one come back\n"
  .string "for the {STR_VAR_3}.$"

Aide_Text_NoPokedexComeBackForPlayerItem::
  .string "…Oh. You don't have a POKéDEX.\p"
  .string "When you get one come back\n"
  .string "for the {STR_VAR_2}'s\l"
  .string "{STR_VAR_3}.$"

Aide_Text_GetEnoughMonsComeBackForItem::
  .string "…Oh. I see.\p"
  .string "When you get {STR_VAR_1} kinds of POKéMON,\n"
  .string "come back for the {STR_VAR_3}.$"

Aide_Text_GetEnoughMonsComeBackForPlayerItem::
  .string "…Oh. I see.\p"
  .string "When you get {STR_VAR_1} kinds of POKéMON,\n"
  .string "come back for {STR_VAR_2}'s\l"
  .string "{STR_VAR_3}.$"

Aide_Text_GiveItemIfCaughtEnough::
  .string "Hi! Remember me?\n"
  .string "I'm one of PROF. OAK's AIDES.\p"
  .string "If your POKéDEX has complete data\n"
  .string "on {STR_VAR_1} species, I'm supposed to\l"
  .string "give you a reward.\p"
  .string "OAK gave me this\n"
  .string "{STR_VAR_3} for you.\p"
  .string "So, {PLAYER}, let me ask you.\p"
  .string "Have you gathered data on at least\n"
  .string "{STR_VAR_1} kinds of POKéMON?$"

Aide_Text_GivePlayerItemIfCaughtEnough::
  .string "Hi! Remember me?\n"
  .string "I'm one of PROF. OAK's AIDES.\p"
  .string "If your POKéDEX has complete data\n"
  .string "on {STR_VAR_1} species, I'm supposed to\l"
  .string "give you a reward.\p"
  .string "OAK gave me {STR_VAR_2}'s\n"
  .string "{STR_VAR_3}.\p"
  .string "So, {PLAYER}, let me ask you.\p"
  .string "Have you gathered data on at least\n"
  .string "{STR_VAR_1} kinds of POKéMON?$"
