Archipelago_Text_PlayerFoundArchipelagoItem::
    .string "{PLAYER} found an ARCHIPELAGO ITEM!$"

Archipelago_Text_PlayerFoundOwnItem::
    .string "{PLAYER} received one {STR_VAR_2}!$"

Archipelago_Text_PlayerFoundPlayersItem::
    .string "{PLAYER} found {STR_VAR_1}'s\n"
    .string "{STR_VAR_2}!$"

Archipelago_Text_FlyToPalletTown::
    .string "{PLAYER} can now fly to\n"
    .string "PALLET TOWN!$"

Archipelago_Text_FlyToViridianCity::
    .string "{PLAYER} can now fly to\n"
    .string "VIRIDIAN CITY!$"

Archipelago_Text_FlyToPewterCity::
    .string "{PLAYER} can now fly to\n"
    .string "PEWTER CITY!$"

Archipelago_Text_FlyToCeruleanCity::
    .string "{PLAYER} can now fly to\n"
    .string "CERULEAN CITY!$"

Archipelago_Text_FlyToLavenderTown::
    .string "{PLAYER} can now fly to\n"
    .string "LAVENDER TOWN!$"

Archipelago_Text_FlyToVermilionCity::
    .string "{PLAYER} can now fly to\n"
    .string "VERMILION CITY!$"

Archipelago_Text_FlyToCeladonCity::
    .string "{PLAYER} can now fly to\n"
    .string "CELADON CITY!$"

Archipelago_Text_FlyToFuchsiaCity::
    .string "{PLAYER} can now fly to\n"
    .string "FUCHSIA CITY!$"

Archipelago_Text_FlyToCinnabarIsland::
    .string "{PLAYER} can now fly to\n"
    .string "CINNABAR ISLAND!$"

Archipelago_Text_FlyToIndigoPlateau::
    .string "{PLAYER} can now fly to the\n"
    .string "INDIGO PLATEAU!$"

Archipelago_Text_FlyToSaffronCity::
    .string "{PLAYER} can now fly to\n"
    .string "SAFFRON CITY!$"

Archipelago_Text_FlyToOneIsland::
    .string "{PLAYER} can now fly to\n"
    .string "ONE ISLAND!$"

Archipelago_Text_FlyToTwoIsland::
    .string "{PLAYER} can now fly to\n"
    .string "TWO ISLAND!$"

Archipelago_Text_FlyToThreeIsland::
    .string "{PLAYER} can now fly to\n"
    .string "THREE ISLAND!$"

Archipelago_Text_FlyToFourIsland::
    .string "{PLAYER} can now fly to\n"
    .string "FOUR ISLAND!$"

Archipelago_Text_FlyToFiveIsland::
    .string "{PLAYER} can now fly to\n"
    .string "FIVE ISLAND!$"

Archipelago_Text_FlyToSixIsland::
    .string "{PLAYER} can now fly to\n"
    .string "SIX ISLAND!$"

Archipelago_Text_FlyToSevenIsland::
    .string "{PLAYER} can now fly to\n"
    .string "SEVEN ISLAND!$"

Archipelago_Text_FlyToRoute4::
    .string "{PLAYER} can now fly to\n"
    .string "ROUTE 4!$"

Archipelago_Text_FlyToRoute10::
    .string "{PLAYER} can now fly to\n"
    .string "ROUTE 10!$"

Archipelago_Text_Received10Coins::
    .string "{PLAYER} received 10 COINS!$"

Archipelago_Text_Received20Coins::
    .string "{PLAYER} received 20 COINS!$"

Archipelago_Text_Received40Coins::
    .string "{PLAYER} received 40 COINS!$"

Archipelago_Text_Received100Coins::
    .string "{PLAYER} received 100 COINS!$"
