Text_OhThatsEnoughBadgesGoRightAhead::
	.string "Oh! You've got enough BADGES!\n"
	.string "Go right ahead.$"

Text_OhThatsEnoughGymsGoRightAhead::
	.string "Oh! You've beaten enough GYMS!\n"
	.string "Go right ahead.$"

Text_OnlyPassWithXBadges::
	.string "You can pass here only if you have\n"
	.string "{STR_VAR_1} BADGES.$"

Text_OnlyPassWithBadge::
	.string "You can pass here only if you have\n"
	.string "{STR_VAR_1} BADGE.$"

Text_OnlyPassWithXGyms::
	.string "You can pass here only if you have\n"
	.string "beaten {STR_VAR_1} GYMS.$"

Text_OnlyPassWithGym::
	.string "You can pass here only if you have\n"
	.string "beaten {STR_VAR_1} GYM.$"

Text_GoodLuckWithEliteFour::
	.string "Good luck challenging the\n"
	.string "ELITE FOUR!$"
