Text_ObtainedItem::
	.string "{PLAYER} received one {STR_VAR_2}!$"

Text_ObtainedTMHM::
	.string "{PLAYER} received one {STR_VAR_2}!\n"
	.string "It contains {STR_VAR_1}.$"

Text_ObtainedBadge::
	.string "{PLAYER} received the {STR_VAR_2}!$"

Text_ObtainedCoins::
	.string "{PLAYER} received {STR_VAR_2}!$"

Text_BagIsFull::
	.string "The BAG is full…$"

Text_PutItemAway::
	.string "{PLAYER} put the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3}.$"

Text_FoundItem::
	.string "{PLAYER} found one {STR_VAR_2}!$"

Text_FoundTMHM::
	.string "{PLAYER} found a {STR_VAR_2}!\n"
	.string "It contains {STR_VAR_1}.$"

Text_FoundBadge::
	.string "{PLAYER} found the {STR_VAR_2}!$"

Text_FoundCoins::
	.string "{PLAYER} found {STR_VAR_2}!$"

Text_ObtainedFlyUnlock::
	.string "{PLAYER} can now fly to\n"
	.string "{STR_VAR_2}!$"

Text_ObtainedLedgeJump::
	.string "{PLAYER} can now jump down ledges!$"

Text_TooBadBagFull::
	.string "Too bad!\n"
	.string "The BAG is full…$"

Text_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

Text_DecorTransferredToPC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"
