ThreeIsland_House1_Text_YoureAlwaysSoCool::
    .string "LOSTELLE: Hi, {PLAYER}!\n"
    .string "You're always so cool!\p"
    .string "I'll make lunch for you, too, one\n"
    .string "day, {PLAYER}.$"

ThreeIsland_House1_Text_ThanksAgain::
    .string "LOSTELLE: Thanks again for saving\n"
    .string "me. I have something to give you.$"

ThreeIsland_House1_Text_RareRocksGemsDisplayed::
    .string "Rare rocks and gems are displayed.$"

