SixIsland_PokemonCenter_1F_Text_SomethingHiddenOnThisIsland::
    .string "For ten years, I've searched for\n"
    .string "RUINS.\p"
    .string "No, make that twenty years.\p"
    .string "I get this feeling that there's\n"
    .string "something hidden on this island.$"

SixIsland_PokemonCenter_1F_Text_SomeMonsEvolveByTradingWithHeldItem::
    .string "You know of POKéMON that evolve\n"
    .string "only upon trading, yes?\p"
    .string "But did you know that there are\n"
    .string "still others?\p"
    .string "Some POKéMON evolve only when\n"
    .string "traded while holding specific items.$"

