SilphCo_1F_Text_WelcomePresidentInBoardroom::
    .string "Welcome.\p"
    .string "The PRESIDENT is in the boardroom\n"
    .string "on 11F.$"

SilphCo_1F_Text_TakeThisCardKey::
    .string "Welcome.\p"
    .string "I heard that you dealt with\n"
    .string "TEAM ROCKET.\p"
    .string "Take this CARD KEY as thanks.$"

SilphCo_1F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "1F$"

