CinnabarIsland_Text_DoorIsLocked::
    .string "The door is locked…$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "CINNABAR GYM's BLAINE is quite the\n"
    .string "odd fellow.\p"
    .string "He's lived on the island since way\n"
    .string "before the LAB was built.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Scientists conduct experiments \n"
    .string "in the burned-out building.\p"
    .string "You know, the one they call the\n"
    .string "POKéMON MANSION.$"

CinnabarIsland_Text_IslandSign::
    .string "CINNABAR ISLAND\n"
    .string "The Fiery Town of Burning Desire$"

CinnabarIsland_Text_PokemonLab::
    .string "POKéMON LAB$"

CinnabarIsland_Text_GymSign::
    .string "CINNABAR ISLAND POKéMON GYM\n"
    .string "LEADER: BLAINE\l"
    .string "The Hotheaded Quiz Master!$"

CinnabarIsland_Text_NoLetter::
    .string "No one is allowed in without\n"
    .string "first getting permission from the\l"
    .string "POKéMON LAB.\p"
    .string "A number of people have been\n"
    .string "breaking in to loot the place.$"

CinnabarIsland_Text_FoundLetter::
    .string "No one is allowed in without\n"
    .string "first getting permission from the\l"
    .string "POKéMON LAB.$"

CinnabarIsland_Text_GiveLetter::
    .string "{PLAYER} handed the LETTER\n"
    .string "to the POLICEMAN.$"

CinnabarIsland_Text_YouCanHeadIn::
    .string "Oh! A letter of entry from the\n"
    .string "POKéMON LAB.\p"
    .string "Just be careful, this place has\n"
    .string "long since been abandoned.$"

CinnabarIsland_Text_BeCareful::
    .string "Feel free to look around as much\n"
    .string "as you would like.\p"
    .string "Just be careful, this place has\n"
    .string "long since been abandoned.$"
