FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPleaseItem::
    .string "I wish to see a POKéMON.\n"
    .string "A darling {STR_VAR_1}.\p"
    .string "I want to see one right away.\n"
    .string "Please, make my wish come true.\p"
    .string "If you do, I'll have SEBASTIAN\n"
    .string "give you this {STR_VAR_3}.$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPleasePlayerItem::
    .string "I wish to see a POKéMON.\n"
    .string "A darling {STR_VAR_1}.\p"
    .string "I want to see one right away.\n"
    .string "Please, make my wish come true.\p"
    .string "If you do, I'll have SEBASTIAN\n"
    .string "give you {STR_VAR_2}'s\l"
    .string "{STR_VAR_3}.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .string "SELPHY: Oh, hello, there.\p"
    .string "Oh, my gracious. That must be the\n"
    .string "{STR_VAR_1} you caught for me.\p"
    .string "Giggle…\n"
    .string "I see a resemblance to you.\p"
    .string "Thank you so kindly.\p"
    .string "… …  … …  … …\n"
    .string "Is something the matter?\p"
    .string "You may leave.\p"
    .string "… …  … …  … …\n"
    .string "Oh, fine. I understand now.\p"
    .string "SEBASTIAN!\n"
    .string "I need you here this instant!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .string "Butler: Yes, my lady.$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .string "SELPHY: See to it that this person\n"
    .string "is given a token of appreciation.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .string "Butler: I shall do as you bid,\n"
    .string "my lady.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .string "Butler: I sincerely thank you for\n"
    .string "pleasing Lady SELPHY.\p"
    .string "Please accept this as her thanks…$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .string "SELPHY: I wish you the best of\n"
    .string "luck.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .string "Butler: The smile of Lady SELPHY\n"
    .string "has the brilliance of the sun.\p"
    .string "Please, I beg you to bring joy\n"
    .string "to Lady SELPHY.$"

