TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "Hey, but listen! I'm begging you,\n"
    .string "you have to go to THREE ISLAND.\p"
    .string "If anything were to happen to my\n"
    .string "LOSTELLE…\p"
    .string "My place is the house with the red\n"
    .string "roof on THREE ISLAND.\p"
    .string "She may just show up late here,\n"
    .string "so I can't run off anywhere.\p"
    .string "That's why I have to get you to do\n"
    .string "me this big favor.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "I'm sorry.\n"
    .string "We're not running any games today.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "We'll get the games going soon\n"
    .string "for you!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "So you rescued LOSTELLE?\n"
    .string "How can I thank you?\p"
    .string "LOSTELLE, darling, forgive me!\p"
    .string "Daddy didn't know you were scared\n"
    .string "and in trouble!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "LOSTELLE: It's okay, Daddy.\n"
    .string "I got to be friends with {PLAYER}!$"

TwoIsland_JoyfulGameCorner_Text_DontHaveNeededMeteorite::
    .string "I love rare rocks and gems.\p"
    .string "If you happen to find any I'll\n"
    .string "give you something good in return.$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "Oh, what's that?\n"
    .string "You're saying that this is for me?\p"
    .string "How did you know that I love rare\n"
    .string "rocks and gems?\p"
    .string "You sure know how to make a guy\n"
    .string "happy.$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "{PLAYER} handed the METEORITE\n"
    .string "to LOSTELLE's daddy.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "Oh, I see, this is from BILL!\n"
    .string "You have to thank him for me!\p"
    .string "You know, you've been fantastic.\n"
    .string "I want you to have this.$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "All right, I'll get the GAME CORNER\n"
    .string "running right away.\p"
    .string "You have to come visit with a\n"
    .string "friend.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "Listen, listen!\p"
    .string "Please show me you being cool\n"
    .string "again!$"

