PokemonMansion_2F_Text_ArnieIntro::
    .string "I can't get out!\n"
    .string "This old place is one big puzzle.$"

PokemonMansion_2F_Text_ArnieDefeat::
    .string "Oh, no!\n"
    .string "My bag of loot!$"

PokemonMansion_2F_Text_ArniePostBattle::
    .string "The switches here open and close\n"
    .string "alternating sets of doors.$"

PokemonMansion_2F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "Diary: July 5\n"
    .string "Guyana, South America\p"
    .string "A new POKéMON was discovered deep\n"
    .string "in the jungle.$"

PokemonMansion_2F_Text_ChristenedDiscoveredMonMew::
    .string "Diary: July 10\n"
    .string "We christened the newly discovered\l"
    .string "POKéMON, MEW.$"

