CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "I came to visit the CINNABAR GYM,\n"
    .string "but the door is locked tight.\p"
    .string "There should be a key for it\n"
    .string "somewhere.\p"
    .string "Could it be in that burned-out\n"
    .string "mansion?\p"
    .string "The GYM LEADER's friend used to\n"
    .string "live there, they say.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "Do you have lots of friends?\p"
    .string "Linking up with the usual friends\n"
    .string "is fun, of course.\p"
    .string "But how about visiting the\n"
    .string "UNION ROOM every so often?\p"
    .string "Who knows, you may end up making\n"
    .string "new friends.\p"
    .string "I think it would be worth your time\n"
    .string "to check the UNION ROOM.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "POKéMON can still learn techniques\n"
    .string "after canceling evolution.\p"
    .string "Evolution can wait until new moves\n"
    .string "have been learned.$"

CinnabarIsland_PokemonCenter_1F_Text_HeyIfItIsntPlayer::
    .string "Huh?\n"
    .string "Hey, if it isn't {PLAYER}!$"

CinnabarIsland_PokemonCenter_1F_Text_TakeThisPassToOneIsland::
    .string "Look, it's me, BILL.\n"
    .string "Long time no see!\p"
    .string "I hope you're still using my\n"
    .string "PC system.\p"
    .string "Well, listen, since we met up here,\n"
    .string "how about I give you this?$"

CinnabarIsland_PokemonCenter_1F_Text_ExplainTriPass::
    .string "There's this little island in the far\n"
    .string "south called ONE ISLAND.\p"
    .string "A friend invited me, so I'm on my\n"
    .string "way out there.\p"
    .string "That PASS is for the ferry service\n"
    .string "serving the SEVII ISLANDS.\p"
    .string "It will let you travel between the\n"
    .string "ISLANDS ONE, TWO, and THREE.$"

CinnabarIsland_PokemonCenter_1F_Text_ShouldBeGoing::
    .string "Well, I should be heading off.\p"
    .string "Remember to come visit me on\n"
    .string "ONE ISLAND when you have the time.$"

