PewterCity_Text_ClefairyCameFromMoon::
    .string "CLEFAIRY came from the moon.\n"
    .string "That's what the rumor is.\p"
    .string "They appeared after MOON STONES\n"
    .string "fell on MT. MOON.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "There aren't many serious POKéMON\n"
    .string "TRAINERS here.\p"
    .string "They're all like BUG CATCHERS,\n"
    .string "you know, just hobbyists.\p"
    .string "But PEWTER GYM's BROCK isn't like\n"
    .string "that, not one bit.$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "Did you check out the MUSEUM?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "Weren't those fossils from MT. MOON\n"
    .string "amazing?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Really?\n"
    .string "You absolutely have to go!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "This is it, the MUSEUM.\p"
    .string "You have to pay to get in, but it's\n"
    .string "worth it. See you around!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Psssst!\n"
    .string "Do you know what I'm doing?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "That's right!\n"
    .string "It's hard work!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "I'm spraying REPEL to keep wild\n"
    .string "POKéMON out of my garden!$"

PewterCity_Text_BrocksLookingForChallengers::
    .string "You're a TRAINER, right?\p"
    .string "BROCK's looking for new\n"
    .string "challengers.$"

PewterCity_Text_GoTakeOnBrock::
    .string "If you have the right stuff,\n"
    .string "go take on BROCK!$"

PewterCity_Text_CanGoThisWay::
    .string "Hey, you can't go this way until…\p"
    .string "Oh! You've already done what I\n"
    .string "was going to tell you to do.\p"
    .string "I'll get outta your way then.$"

PewterCity_Text_NeedToBeatBrock::
    .string "Hey, you can't go this way until\n"
    .string "you've beaten the PEWTER GYM.$"

PewterCity_Text_NeedToBeatAnyGym::
    .string "Hey, you can't go this way until\n"
    .string "you've beaten one of the GYMS.$"

PewterCity_Text_NeedToHaveBoulderBadge::
    .string "Hey, you can't go this way until\n"
    .string "you've got the BOULDER BADGE.$"

PewterCity_Text_NeedToHaveAnyBadge::
    .string "Hey, you can't go this way until\n"
    .string "you've got one of the BADGES.$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "TRAINER TIPS\p"
    .string "All POKéMON that appear in battle,\n"
    .string "however briefly, earn EXP Points.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "NOTICE!\p"
    .string "Thieves have been stealing POKéMON\n"
    .string "fossils from MT. MOON.\p"
    .string "Please call the PEWTER POLICE if\n"
    .string "you have any information.$"

PewterCity_Text_MuseumOfScience::
    .string "PEWTER MUSEUM OF SCIENCE$"

PewterCity_Text_GymSign::
    .string "PEWTER CITY POKéMON GYM\n"
    .string "LEADER: BROCK\l"
    .string "The Rock-Solid POKéMON TRAINER!$"

PewterCity_Text_CitySign::
    .string "PEWTER CITY\n"
    .string "A Stone Gray City$"

PewterCity_Text_OhPlayer::
    .string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "I'm glad I caught up to you.\n"
    .string "I'm PROF. OAK's AIDE.\p"
    .string "I've been asked to deliver this,\n"
    .string "so here you go.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} received the\n"
    .string "RUNNING SHOES from the AIDE.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} switched shoes with the\n"
    .string "RUNNING SHOES.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Press the B Button to run.\n"
    .string "But only where there's room to run!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Well, I must be going back to\n"
    .string "the LAB.\p"
    .string "Bye-bye!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "There's a letter attached…\p"
    .string "Dear {PLAYER},\p"
    .string "Here is a pair of RUNNING SHOES\n"
    .string "for my beloved challenger.\p"
    .string "Remember, I'll always cheer for\n"
    .string "you! Don't ever give up!\p"
    .string "From Mom$"

