SilphCo_10F_MapScripts::
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_10F_OnLoad
	.byte 0

SilphCo_10F_OnLoad::
	call_if_unset FLAG_SILPH_10F_DOOR, EventScript_Close10FDoor
	end

SilphCo_10F_EventScript_WorkerF::
	lock
	faceplayer
	specialvar VAR_RESULT, ArchipelagoSpecial_AreCardKeysSplit
	goto_if_eq VAR_RESULT, FALSE, SilphCo_10F_EventScript_WorkerFGaveCardKey
	goto_if_set FLAG_GOT_10F_CARD_KEY, SilphCo_10F_EventScript_WorkerFGaveCardKey
	call EventScript_TakeThisCardKey
Archipelago_Target_NPC_Gift_FLAG_GOT_10F_CARD_KEY::
	giveitem ITEM_CARD_KEY_10F, 1, FLAG_GOT_10F_CARD_KEY
	release
	end

SilphCo_10F_EventScript_WorkerFGaveCardKey::
	goto_if_ge VAR_MAP_SCENE_SILPH_CO_11F, 1, SilphCo_10F_EventScript_WorkerFRocketsGone
	msgbox SilphCo_10F_Text_WaaaImScared
	release
	end

SilphCo_10F_EventScript_WorkerFRocketsGone::
	msgbox SilphCo_10F_Text_KeepMeCryingASecret
	release
	end

SilphCo_10F_EventScript_FloorSign::
	msgbox SilphCo_10F_Text_FloorSign, MSGBOX_SIGN
	end

SilphCo_10F_EventScript_Travis::
	trainerbattle_single TRAINER_SCIENTIST_TRAVIS, SilphCo_10F_Text_TravisIntro, SilphCo_10F_Text_TravisDefeat
	msgbox SilphCo_10F_Text_TravisPostBattle, MSGBOX_AUTOCLOSE
	end

SilphCo_10F_EventScript_Grunt::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_39, SilphCo_10F_Text_GruntIntro, SilphCo_10F_Text_GruntDefeat
	msgbox SilphCo_10F_Text_GruntPostBattle, MSGBOX_AUTOCLOSE
	end
