Text_DreamEaterTeach::
    .string "Yawn!\n"
    .string "I must have dozed off in the sun.\p"
    .string "I had this weird dream about\n"
    .string "a DROWZEE using {STR_VAR_1}.\p"
    .string "And…\n"
    .string "I learned how to eat dreams…\p"
    .string "Oogh, this is too spooky!\p"
    .string "Let me teach it to a POKéMON so\n"
    .string "I can forget about it!$"

Text_DreamEaterDeclined::
    .string "…Snore…$"

Text_DreamEaterWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "{STR_VAR_1}?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "I…can't eat…anymore…$"

ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Those POKé BALLS at your waist!\n"
    .string "You have POKéMON, don't you?\p"
    .string "It's great that you can carry and\n"
    .string "use POKéMON anytime, anywhere.$"

ViridianCity_Text_OnlyOpenWithXBadges::
    .string "The GYM is closed until the GYM\n"
    .string "LEADER returns.\p"
    .string "You need to have {STR_VAR_1} BADGES\n"
    .string "for it to open.$"

ViridianCity_Text_OnlyOpenWithBadge::
    .string "The GYM is closed until the GYM\n"
    .string "LEADER returns.\p"
    .string "You need to have {STR_VAR_1} BADGE\n"
    .string "for it to open.$"

ViridianCity_Text_OnlyOpenWithXGyms::
    .string "The GYM is closed until the GYM\n"
    .string "LEADER returns.\p"
    .string "You need to beat {STR_VAR_1} GYMS\n"
    .string "for it to open.$"

ViridianCity_Text_OnlyOpenWithGym::
    .string "The GYM is closed until the GYM\n"
    .string "LEADER returns.\p"
    .string "You need to beat {STR_VAR_1} GYM\n"
    .string "for it to open.$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VIRIDIAN GYM's LEADER returned!$"

ViridianCity_Text_YoullNeedThis::
    .string "If you want to challenge him\n"
    .string "you'll need this.$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "You want to know about the two\n"
    .string "kinds of caterpillar POKéMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Oh, okay then!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE has no poison,\n"
    .string "but WEEDLE does.\p"
    .string "Watch that your POKéMON aren't\n"
    .string "stabbed by WEEDLE's POISON STING.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Oh, Grandpa!\n"
    .string "Don't be so mean!\p"
    .string "I'm so sorry.\n"
    .string "He hasn't had his coffee yet.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "I go shopping in PEWTER CITY\n"
    .string "occasionally.\p"
    .string "I have to take the winding trail in\n"
    .string "VIRIDIAN FOREST when I go.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "I absolutely forbid you from\n"
    .string "going through here!\p"
    .string "This is private property!$"

ViridianCity_Text_TakeThis::
    .string "Well, now I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "Sorry about being so mean before.\p"
    .string "You know what, I'll give you this\n"
    .string "to make up for it.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "If there's something you don't\n"
    .string "understand, watch that.\p"
    .string "It will teach you about the basics\n"
    .string "of being a POKéMON TRAINER.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, are you filling your\n"
    .string "POKéDEX?\p"
    .string "At first, focus on weakening the\n"
    .string "POKéMON before trying to catch it.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, is my old TEACHY TV\n"
    .string "helping you?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN CITY \n"
    .string "The Eternally Green Paradise$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "TRAINER TIPS\p"
    .string "Catch POKéMON and expand your\n"
    .string "collection.\p"
    .string "The more you have, the easier it\n"
    .string "is to battle.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "TRAINER TIPS\p"
    .string "The battle moves of POKéMON are\n"
    .string "limited by their POWER POINTS, PP.\p"
    .string "To replenish PP, rest your tired\n"
    .string "POKéMON at a POKéMON CENTER.$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "The GYM's doors are locked until\n"
    .string "the GYM LEADER returns.$"

