FiveIsland_LostCave_Room10_Text_SelphyIntro::
    .string "W-what do you intend to do with\n"
    .string "me?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
    .string "Oh… I was afraid that you meant to\n"
    .string "harm me.$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
    .string "I am so glad that you happened\n"
    .string "here.\p"
    .string "I grew rather bored of walking,\n"
    .string "and I am feeling fatigued.\p"
    .string "May I ask you to take me home\n"
    .string "from here?$"

FiveIsland_LostCave_Room10_Text_StillThingsToDo::
    .string "You still have things to do here?\p"
    .string "Just let me know when you are\n"
    .string "ready to leave.$"

FiveIsland_LostCave_Room10_Text_GoToResortGoregous::
    .string "Do you want to go to\n"
    .string "RESORT GORGEOUS?$"

