FiveIsland_LostCave_Room10_Text_SelphyIntro::
    .string "W-what do you intend to do with\n"
    .string "me?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
    .string "Oh… I was afraid that you meant to\n"
    .string "harm me.$"

FiveIsland_LostCave_Room10_Text_GoingToHeadHome::
    .string "I apologize for being so\n"
    .string "frantic at first.\p"
    .string "Honestly, I've grown bored of\n"
    .string "walking around this cave.\p"
    .string "I'm going to head home now.$"

