FourIsland_Text_IslandSign::
    .string "FOUR ISLAND\n"
    .string "The Warm, Blue, Floe Island$"

FourIsland_Text_LoreleiHasReturned::
    .string "LORELEI has returned.\p"
    .string "Did she find the city life too\n"
    .string "stressful, I wonder?$"

FourIsland_Text_LoreleiMetLaprasAsChild::
    .string "LORELEI has gone back.\p"
    .string "The LAPRAS she has, I imagine it\n"
    .string "to be the one she met as a child.\p"
    .string "I believe it was in ICEFALL CAVE\n"
    .string "that she caught it.\p"
    .string "Perhaps that POKéMON has been with\n"
    .string "her ever since.$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
    .string "Oh, you found me!\n"
    .string "Please don't tell LORELEI.\p"
    .string "Did you know that LORELEI has lots\n"
    .string "and lots of stuffed dolls?\p"
    .string "Every time she comes back to\n"
    .string "FOUR ISLAND, her collection grows!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "Ooh, chilly!\p"
    .string "I made a slushie using ice I\n"
    .string "shaved inside ICEFALL CAVE.\p"
    .string "It's chilly and tasty!$"

FourIsland_Text_LoreleisHouse::
    .string "LORELEI'S HOUSE$"

